// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMJziQIOkE8Nqz-nR4F3e5-YM2W5S65tI',
    appId: '1:400549962877:web:6f6d214b5c1de159d87d14',
    messagingSenderId: '400549962877',
    projectId: 'fir-login-442e4',
    authDomain: 'fir-login-442e4.firebaseapp.com',
    storageBucket: 'fir-login-442e4.appspot.com',
    measurementId: 'G-LPDSED8ZY1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUawn0bZuEUllbUvY4QaDzWm6oKrOu0q0',
    appId: '1:400549962877:android:8e0992380c71a530d87d14',
    messagingSenderId: '400549962877',
    projectId: 'fir-login-442e4',
    storageBucket: 'fir-login-442e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMM-tAro1pyInB1thO0XogsRrJCK6-L4k',
    appId: '1:400549962877:ios:5437de8e802f595dd87d14',
    messagingSenderId: '400549962877',
    projectId: 'fir-login-442e4',
    storageBucket: 'fir-login-442e4.appspot.com',
    iosClientId: '400549962877-iatp7dg3c5qabi0ehre4ee17l4gimkk6.apps.googleusercontent.com',
    iosBundleId: 'com.dh.uilogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMM-tAro1pyInB1thO0XogsRrJCK6-L4k',
    appId: '1:400549962877:ios:5437de8e802f595dd87d14',
    messagingSenderId: '400549962877',
    projectId: 'fir-login-442e4',
    storageBucket: 'fir-login-442e4.appspot.com',
    iosClientId: '400549962877-iatp7dg3c5qabi0ehre4ee17l4gimkk6.apps.googleusercontent.com',
    iosBundleId: 'com.dh.uilogin',
  );
}
